# -*- coding: utf-8 -*-
"""Hands-on Activity 1.0 Python Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EgxDQgpYkJGLoU_4mj9Nil1HwUMgtj5b

Python Variables
"""

x = float (1)
a, b = 0, -1
a, b, c = "Katarina", "Rue", "Nate"

print('This is a sample')
print(a)
print(c)

"""Casting"""

print(x)

"""Type()Function"""

y = "Romblon"

print(type(y))
print(type(x))

"""Double quotes and Single quotes"""

#h = "Baby, Goodnight"
h = 'Baby, Goodnight'
v = 1
V = 3

print(h)
print(v)
print(v+1)

"""Multiple Variables"""

x, y, z = "I", "Miss", 'You'

print(x)
print(y)
print(z)
print(x, y, z)

"""One Value to Multiple Variables"""

x = y = z = "Hello"
print(x, y, z)
print(x)
print(y)
print(z)

"""Output Variables"""

x = "Python"
y = "I love"

print("I love " + x)
print(y + " " + x)

"""Arithmetic Operations"""

k = 2
l = 3
print(k>>2)#shift right twice
print(k<<2)#shift left twice

m = 5
o = 2
n = 7

print(m+n)
print(m-n)
print(o*n)
print(int(m/o))
print(5/m)
print(5%m)
print(5//m)
print(5**2)

"""Boolean Operators"""

k = 2
l = 3
print(k>>2)#shift right twice
print(k<<2)#shift left twice

"""Relational Operators"""

t = 1
v = 2

print(t>v)
print(v==t)

"""Logical Operators"""

print(v<t and t==t)
print(v<t or t==v)
print(not (v<t or t==v))

"""Identity Operators"""

print(v is k)
print(v is not k)